imports:
  - https://raw.githubusercontent.com/dotnet/crank/main/src/Microsoft.Crank.Jobs.Bombardier/bombardier.yml

jobs:
  server:
    source:
      repository: https://github.com/Ranada/learning-c-sharp
      branchOrCommit: main
      project: MicrosoftTraining/mslearn-create-web-api-aspnet-core/ContosoPizzaApi/ContosoPizzaApi.csproj
    readyStateText: Application started.

scenarios:
  api:
    application:
      job: server
    load:
      job: bombardier
      variables:
        serverPort: 5000
        path: /

profiles:
  local:
    variables:
      serverAddress: localhost
    jobs: 
      application:
        endpoints: 
          - http://localhost:5010
      load:
        endpoints: 
          - http://localhost:5010